### ISSUE TITLE
V3?

### ISSUE THREAD

**Issue by noonasGit** [Mavireck/Python-Screen-Stack-Manager#2]
hello there!

I see that v3 was coming - still on the way??

**Comment by Mavireck** [comment]
Hello, 
Sadly no, I have been too busy to work on it and I have left it on hold. The v2 branch should still work, although keep in mind:
- I had only just started learning Python when I wrote this, so now there are a lot of things I would implement differently (hence v3)
- the performance is quite disappointing if you app requires interaction. I considerered at some point learning Go or Rust and implementing it all over again, but that would go against the initial goal which was to have a fast and easy scripting library to quickly write simple apps on the kobo.
- the touch interaction probably only works on a limited range of kobos (like the aura h2o v1)

Your message reminded me to push the v3 I have locally on my computer, and see how well it works so far. It might be grounds for further improvements by other users!
Feel free to contribute however!

**Comment by noonasGit** [comment]
Hey there!Thanks, I will for sure take a look at what you posted.I too started learning Python (have been hacking around the YAWK).I have added modules, improved stability etc to it.I do like the fact of interaction of touch - tap here to indicate you took in the garbage etc.I will take a look and see if I can use what you made to improve my home hub dashboard. Jonas JohanssonIT Support UX Expert Mac SpecialistOn Feb 25, 2023, at 05:09, Mavireck ***@***.***> wrote:﻿
Hello,
Sadly no, I have been too busy to work on it and I have left it on hold. The v2 branch should still work, although keep in mind:

I had only just started learning Python when I wrote this, so now there are a lot of things I would implement differently (hence v3)
the performance is quite disappointing if you app requires interaction. I considerered at some point learning Go or Rust and implementing it all over again, but that would go against the initial goal which was to have a fast and easy scripting library to quickly write simple apps on the kobo.
the touch interaction probably only works on a limited range of kobos (like the aura h2o v1)

Your message reminded me to push the v3 I have locally on my computer, and see how well it works so far. It might be grounds for further improvements by other users!
Feel free to contribute however!

**Comment by noonasGit** [comment]
Hey there!

I tried to pull the latest from this but it seems incomplete?
the examples refers to files that are not part of the repo. 

"import sys
sys.path.append("../")
from PSSM import Stack
from PSSM.elements import Demo, Static, Rectangle
from time import sleep
from PSSM.styles import DEMO as DEMO_STYLE
from PSSM.styles import DEFAULT as DEFAULT_STYLE"

is the PSSM core in a separate package?

**Comment by noonasGit** [comment]
what I would like to do is to add touch to my dashboard - your package seems to be able to do so.
I also tried the latest dashboard (KoboDashboardWithPythonLauncherAndWA)
but after unzipping and trying it, it says
"Traceback (most recent call last):
  File "/mnt/onboard/.adds/mavireck/Kobo-Dashboard/dashboard.py", line 1398, in <module>
    FBInk.fbink_add_ot_font("fonts/Merriweather-Regular.ttf", FBInk.FNT_REGULAR);
TypeError: initializer for ctype 'char *' must be a bytes or list or tuple, not str"

you can email me at noonas@gmail.com

**Comment by Mavireck** [comment]
> Hey there!
> 
> I tried to pull the latest from this but it seems incomplete? the examples refers to files that are not part of the repo.
> 
> "import sys sys.path.append("../") from PSSM import Stack from PSSM.elements import Demo, Static, Rectangle from time import sleep from PSSM.styles import DEMO as DEMO_STYLE from PSSM.styles import DEFAULT as DEFAULT_STYLE"
> 
> is the PSSM core in a separate package?

I do not understand you question. The PSSM core is exactly what is contained in this repo. 
_Stack_ is defined in main.py.
elements and Styles are separate modules which are contained in the respective folders.

**Comment by Mavireck** [comment]
> what I would like to do is to add touch to my dashboard - your package seems to be able to do so. I also tried the latest dashboard (KoboDashboardWithPythonLauncherAndWA) but after unzipping and trying it, it says "Traceback (most recent call last): File "/mnt/onboard/.adds/mavireck/Kobo-Dashboard/dashboard.py", line 1398, in FBInk.fbink_add_ot_font("fonts/Merriweather-Regular.ttf", FBInk.FNT_REGULAR); TypeError: initializer for ctype 'char *' must be a bytes or list or tuple, not str"
> 
> you can email me at [noonas@gmail.com](mailto:noonas@gmail.com)

Updates in FBink, pyFBInk or in Python can have changed this behavior. Again, I have not used my dashboard for a long time so you can expect some debugging to be required, though I do believe PSSM should still work well (at least on a Kobo Aura H2O edition 1, which is the device I use).

Note that my dashboard (the dashboard.py file) does NOT use PSSM at all. I developped PSSM much after working on my dashboard.

**Comment by Mavireck** [comment]
I have pushed the remaining commits from my local hard drive to the master branch. I tested them on my laptop, the test files work. I do not know how well they work on a kobo however. 

From what I remember, v3 (ie master branch) was still widely work in progress, the code was badly organized, but it should be more powerful than v2.

**Comment by Mavireck** [comment]
**V3 update**
I have updated the master branch to fix the ongoing on-screen keyboard work. It now works.
There is no documentation yet for v3, but you can read the example files for information.
